#!/bin/bash
#SBATCH -J Thian_Product_Opt
#SBATCH -o output.%j
#SBATCH -e error.%j
#SBATCH -N 1 -n 1
#SBATCH -p normal
#SBATCH -t 45:00:00
#SBATCH -A DFT-and-EPR-Simulati

module load gaussian

g16 < ThianProd_C.config > ThianProd_C.log
