#!/bin/bash
#SBATCH -J Mn_TRANS_FLIPED_DIRECT
#SBATCH -o output.%j
#SBATCH -e error.%j
#SBATCH -N 1 -n 1
#SBATCH -p normal
#SBATCH -t 42:00:00

module load gaussian

g16 < DirectFlip.config > output.log
