#!/bin/bash
#SBATCH -J TS_Frequency_Analysis_RESTART
#SBATCH -o output.%j
#SBATCH -e error.%j
#SBATCH -N 1 -n 1
#SBATCH -p normal
#SBATCH -t 42:00:00

module load gaussian

g16 < TSFreq_2.config > output.log
