#!/bin/bash
#SBATCH -J MN_TRANS_SEARCH_MnTransSearch_11
#SBATCH -o output.%j
#SBATCH -e error.%j
#SBATCH -N 1 -n 1
#SBATCH -p normal
#SBATCH -t 42:00:00

module load gaussian

g16 < MnTransSearch_11.config > MnTransSearch_11_output.log