#!/bin/bash
#SBATCH -J ANTHRACENE_TS_1
#SBATCH -o output.%j
#SBATCH -e error.%j
#SBATCH -N 1 -n 1
#SBATCH -p normal
#SBATCH -t 42:00:00
#SBATCH -A DFT-and-EPR-Simulati

module load gaussian

g16 < AnthTS_1_Restart_1.config > output.log
